Add a --list-android-packages option.
This is how you would generate the file for the --package-manifest option.

diff --git a/android-sdk-installer b/android-sdk-installer
--- a/android-sdk-installer
+++ b/android-sdk-installer
@@ -32,6 +32,7 @@ function abort_script() {
 ARG_ENV_FILE=""
 ARG_JDK_VER=""
 ARG_INSTALL_DIR=""
+ARG_LIST_ANDROID_PKG_ATOMS=""
 ARG_PKG_MANIFEST=""
 ARG_SDK_TOOLS_FILE=""
 
@@ -85,14 +86,11 @@ function accept_licenses () {
    yes | sdkmanager --licenses
 }
 
-function generate_package_list () {
-   # Basically install every package...
-   local _pkg_list_to_create="$1"
-
-   test -f "$_pkg_list_to_create" || abort_script "get_package_list(): no _pkg_list_to_create passed"
-
+function list_android_package_atoms() {
    # This was really the main thing we kept from the original
    # https://github.com/BuddyBuild/android-sdk-installer/blob/master/android-sdk-installer
+
+   sdkmanager --list --include_obsolete --verbose |\
    egrep '^\S+'      |\
    sed -E '/(---)/d'  |\
    sed -E '/(Info)/d' |\
@@ -112,7 +110,18 @@ function generate_package_list () {
    # emulators no longer really work in our environment
    sed -E '/(system-images)/d' |\
    sed -E '/(^tools)/d' |\
-   sed -E '/(done)/d' > $_pkg_list_to_create
+   sed -E '/(done)/d'
+}
+
+
+function generate_package_list () {
+   # Basically install every package...
+   local _pkg_list_to_create="$1"
+
+   test -f "$_pkg_list_to_create" || abort_script "get_package_list(): no _pkg_list_to_create passed"
+
+   # Recursively call ourselves to generate the package list
+   $0 --install-dir "$ARG_INSTALL_DIR" --list-android-packages > $_pkg_list_to_create
 }
 
 function install_android_sdk_packages() {
@@ -173,6 +182,10 @@ function main () {
             shift
             shift
             ;;
+         -l|--list-android-packages)
+            ARG_LIST_ANDROID_PKG_ATOMS=1
+            shift
+            ;;
          *)
             # unknown option
             positional_args+=("$1")
@@ -184,7 +197,18 @@ function main () {
    # restore positional parameters
    set -- "${POSITIONAL[@]}"
 
+   export ANDROID_HOME="$ARG_INSTALL_DIR/android-sdk-macosx"
+   export TOOLS_DIR="$ANDROID_HOME/tools"
 
+   if test -z "$ARG_INSTALL_DIR"; then
+      echo "Missing --install-dir" >&2
+      return 1
+   fi
+
+   if test -n "$ARG_LIST_ANDROID_PKG_ATOMS"; then
+      list_android_package_atoms
+      return 0
+   fi
 
    # Validate --jdk-version
    local _jdk_version_dir=""
@@ -238,9 +262,6 @@ function main () {
    fi
 
    echo "$0: Installing in: $ARG_INSTALL_DIR"
-   
-   export ANDROID_HOME="$ARG_INSTALL_DIR/android-sdk-macosx"
-   export TOOLS_DIR="$ANDROID_HOME/tools"
 
    echo "$0: Cleaning installation directory: $ARG_INSTALL_DIR"
    rm -rf $ARG_INSTALL_DIR
@@ -256,6 +277,8 @@ function main () {
    update_sdkmanager
 
    # We only need to generate the package list if one wasn't supplied to us
+   # Note: this recursively calls this script, and it assumes the SDK tools
+   # have already been installed.
    if test -z "$ARG_PKG_MANIFEST"; then
       generate_package_list $_package_manifest
    fi
